### ISSUE TITLE
Issue: redirected you too many times

### ISSUE THREAD

**Issue by gauti038** [Venator-Fox/docker-moodle#30]
I am running your images as pods within kubernetes. This is exposed as NodePort and an external nginx redirects traffic to this nodeport. I tried setting the variable MOODLECFG_REVERSEPROXY to True. no Luck. Please help

**Comment by Venator-Fox** [comment]
Sorry for the late reply. I have not tested this in K8s yet.

All that variable does is insert this in the moodle config:
`$CFG->sslproxy = true;`

Does it work when you set it up without https and just have your load balancer use 80?
I have not really tested this with any other LB other than HAProxy.

Can you tell me the process you used to set this up so I can investigate further? I'll try to bring this up in orchestrated environment to reproduce this.
